### ISSUE TITLE
Setting time of day crashes when in a timezone that is behind UTC and it is past midnight in UTC

### ISSUE THREAD

**Issue by jrstrunk** [massivefermion/birl#18] opened 2024-05-01 00:27 UTC
The test function:
```
pub fn birl_set_time_of_day_test() {
  birl.now()
  |> birl.set_time_of_day(birl.TimeOfDay(9, 30, 0, 0))
}
```
fails when it is past 12:00 AM UTC but before (I assume, haven't waited to test it yet) 4:00 AM UTC on a system which has a time zone of EDT(UTC-04).

On my system, `birl.now()` produces `Time(1714523701784880, 158400000000, Some("America/New_York"), Some(247434))`

The stack trace is:
```
birl_set_time_of_day_test
     #{function => <<"to_parts">>,gleam_error => let_assert,line => 1237,
       message => <<"Assertion pattern match failed">>,module => <<"birl">>,
       value => {error,nil}}
     location: birl.to_parts:1237
     stacktrace:
       birl.to_parts
       birl.set_time_of_day
```

I believe a time zone of (UTC-02) would crash between 12:00 AM UTC and 2:00 AM UTC, but I haven't tested it yet because it takes waiting. I believe the issue is when the date of the local time is different than the date of the UTC time, but could be wrong.

I can work around this by setting my system's time zone to either UTC or a timezone ahead of it. I am in the EDT time zone and just randomly started getting crashes after 8pm while working.

EDIT: while I was testing it further I realized converting to UTC from EDT right now (Apr 30, 8:39pm) also changes the month in the calendar date, so maybe that is the issue. I will run the test again tomorrow past 8pm and see.

**Comment by jrstrunk** [comment] 2024-05-01 00:30
Funnily enough, just the other day I was looking into a PhotoPrism bug in production where converting between EDT and UTC fails if the time is past 8pm EDT because the conversion changes the calendar date. Must be a tricky thing ;)

**Comment by massivefermion** [comment] 2024-05-23 09:33
I just changed the timezone of my system to `America/New_York` and changed the time of my system to the problematic range you described. I couldn't reproduce the problem.
Of course the issue is the wrong offset(`158400000000`) which would crash but the thing is, `birl.now()` gave me the correct offset!

Could you run the same code using the js backend and report back the result of `birl.now()`?

**Comment by massivefermion** [comment] 2024-06-02 12:04
Turned out this was happening because the calculations I've been doing on the Erlang target to determine the local offset were not considering an edge case when the month is changing between subsequent days! It should be fixed in the latest version now!
Thanks for the issue

**Closed by massivefermion** 2024-06-02 12:04 UTC

**Comment by jrstrunk** [comment] 2024-06-02 12:08
Great, thanks so much! Sorry I never got chance to help you triage it.
